#!/bin/bash

bat=$(ls /sys/class/power_supply | grep BAT | head -n 1)

if [[ $1 == '--icon' ]]; then
    if [[ $(cat /sys/class/power_supply/BAT0/status) == 'Discharging' ]]; then
        echo '󰁹'
    else
        echo '󰂄'
    fi
elif [[ $1 == '--text' ]]; then
    cat /sys/class/power_supply/BAT0/capacity
fi
