#!/bin/bash

set_vals() {
    icon='󰃞'
    text=$(brightnessctl | grep 'Current brightness:' | cut -d ' ' -f 4 | tr -d '()%')

    eww update BRI_ICON=$icon
    eww update BRI_TEXT=$text
}

if [[ $1 == '--up' ]]; then
    brightnessctl -q set 5%+
elif [[ $1 == '--down' ]]; then
    brightnessctl -q set 5%-
fi

set_vals

if [[ $1 == '--icon' ]]; then
    echo $icon
elif [[ $1 == '--text' ]]; then
    echo $text
fi
