#!/bin/bash

is_connected=$(nmcli g | grep 'connected')
wifi_name=$(nmcli c | grep wlan0 | cut -d ' ' -f 1)

if [[ $is_connected == '' ]]; then
    icon='󰈂'
    text='Disconnected'
else
    if [[ $wifi_name == '' ]]; then
        icon=''
        text='Ethernet'
    else
        icon='󰖩'
        text=$wifi_name
    fi

fi

if [[ $1 == '--icon' ]]; then
    echo $icon
elif [[ $1 == '--text' ]]; then
    echo $text
fi
