## name: Dynamic

selection_foreground    #303446
selection_background    #ca9ee6

background              #303446
foreground              #c6d0f5

color0                  #303446
color1                  #e78284
color2                  #a6d189
color3                  #e5c890
color4                  #8caaee
color5                  #ca9ee6
color6                  #81c8be
color7                  #c6d0f5
color8                  #737994
color9                  #e78284
color10                 #a6d189
color11                 #e5c890
color12                 #8caaee
color13                 #ca9ee6
color14                 #81c8be
color15                 #c6d0f5

cursor                  #c6d0f5
cursor_text_color       #c6d0f5

url_color               #81c8be

active_tab_foreground   #a6d189
active_tab_background   #292c3c
active_tab_font_style   bold-italic
inactive_tab_foreground #c6d0f5
inactive_tab_background #292c3c