#!/bin/bash

main="$HOME/.config/eww/arin/bar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	eww --config "$main" open-many \
        search \
        workspace \
        sys_tray \
        fuzzytime \
        system
}

## Launch or close widgets accordingly
run_eww
