#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 0 1 2 3 4

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        '#a6da95'
bspc config normal_border_color         '#5b6078'
bspc config active_border_color         '#a6da95'

#
# Autostart
#
# Picom
picom --config $HOME/.config/picom.conf &

# Wallpaper
feh --bg-fill /home/younix/Dropbox/Pictures/Wallpapers/catppuccin/normal/wavy_lines_v01_5120x2880.png

# Bar
sh ~/.config/eww/arin/laptop/launch_bar

# Notifications
dunst &

# Keybinds
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

sleep 8

# System Tray
stalonetray &

# Dropbox
dropbox &