#!/bin/bash

ID="$(ip link | awk '/state UP/ {print $2}')"
SSID="$(iwgetid -r)"

check () {
	if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
		if [[ $ID == e* ]]; then
			echo "Ethernet"
			echo ""
		else
			echo "$SSID"
			echo ""
		fi
	else
		echo "Offline"
		echo ""
	fi
}

if [[ $1 == '--text' ]]; then
	check | head -n1
elif [[ $1 == '--icon' ]]; then
	check | tail -n1
fi
