#!/bin/bash

updatequotes() {
uri=$(curl -s "https://api.quotable.io/random?maxLength=90")

echo $uri | jq '.content' |  cut -d "\"" -f 2 > "$HOME/.cache/widget.quote"
echo $uri | jq '.author' |  cut -d "\"" -f 2 > "$HOME/.cache/widget.author"
}

quote=$(cat $HOME/.cache/widget.quote)
author=$(cat $HOME/.cache/widget.author)

if [ "$quote" = "" ] ; then
	  quote="The timeless in you is aware of life's timelessness. And knows that yesterday is but today's memory and tomorrow is today's dream."
    author="Khalil Gibran"
fi

case $1 in
quote)
echo $quote
;;
author)
echo "~ $author ~"
;;
update)
  updatequotes
;;
esac
