#!/bin/bash

hour="$(date +%I)"
min="$(date +%M)"
ap="$(date +%P)"

get_time() {
    echo "$hour:$min"
}

get_ampm() {
    echo "$ap"
}

if [[ $1 == '--text' ]]; then
	get_time
elif [[ $1 == '--ampm' ]]; then
	get_ampm
fi