#!/bin/bash

# Set decoration geometry
berryc border_width 		0
berryc inner_border_width 	7
berryc title_height 		10
berryc edge_gap 			82 20 20 20

# Set decoration colors
berryc focus_color              98971a
berryc unfocus_color            83a598
berryc inner_focus_color        98971a
berryc inner_unfocus_color      83a598
berryc text_focus_color         98971a
berryc text_unfocus_color       83a598

# Other options
berryc set_font             "MesloLGS NF"
berryc smart_place 			"true"
berryc draw_text 			"true"
berryc edge_lock 			"true"
berryc json_status 			"true"
berryc decorate_new 		"true"
berryc pointer_interval 	0
berryc manage 				Dialog|Toolbar|Menu|Splash|Utility 

# Other applications
# Picom
picom --config $HOME/.config/picom.conf &

# Wallpaper
feh --bg-fill /home/younix/Dropbox/Pictures/Wallpapers/gruvbox/light/aaron-VNHHxsVEUho-unsplash.jpg

# Bar
sh ~/.config/eww/arin/laptop/launch_bar

# Notifications
dunst &

# Network Applet
nm-applet --indicator &

# Keybinds
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# Dropbox
dropbox &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
