#!/bin/bash

# playerctl code done by:
# author	Niraj
# github	niraj998

## Get data
[ -n "$(pgrep spotify)" ] && Control="spotify"
Cover="/tmp/.music_cover.jpg"
bkpCover=~/.config/eww/arin/images/music.png
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
    icon="../images/icons/music/stop.svg"
    [ $(playerctl --player=$Control status) = "Playing" ] && icon="../images/icons/music/pause.svg"
    [ $(playerctl --player=$Control status) = "Paused" ] && icon="../images/icons/music/play.svg"
    echo "$icon"
}

## Get song
get_song() {
    title=$(playerctl --player=$Control metadata --format {{title}})
    [ -z "$title" ] && title="Nothing Playing"
    echo "$title"
}

## Get artist
get_artist() {
    artist=$(playerctl --player=$Control metadata --format {{artist}})
    [ -z "$artist" ] && artist="Offline"
    echo "$artist"	
}

## Get album
get_album() {
    album=$(playerctl --player=$Control metadata --format {{album}})
    [ -z "$album" ] && album="Album"
    echo "$album"
}

## Get time
get_time() {
	time=`mpc status | grep "%)" | awk '{print $4}' | tr -d '(%)'`
	if [[ -z "$time" ]]; then
		echo "0"
	else
		echo "$time"
	fi	
}
get_ctime() {
	ctime=`mpc status | grep "#" | awk '{print $3}' | sed 's|/.*||g'`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=`mpc -f %time% current`
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Get cover
get_cover() {
    albumart="$(playerctl --player=$Control metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
    [ $(playerctl --player=$Control metadata mpris:artUrl) ] && curl -s "$albumart" --output $Cover || cp $bkpCover $Cover 
    echo "$Cover"
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl play-pause
elif [[ "$1" == "--next" ]]; then
	{ playerctl next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ playerctl previous; get_cover; }
fi